'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {todayJalali} from '@/lib/jalali';
import FormModal from '@/components/FormModal';
const n=(v:any)=>new Intl.NumberFormat('fa-IR').format(Number(v||0));
export default function Inventory(){
 const[products,setProducts]=useState<any[]>([]),[materials,setMaterials]=useState<any[]>([]),[productOptions,setProductOptions]=useState<any[]>([]);
 const[openMove,setOpenMove]=useState(false),[openMaterial,setOpenMaterial]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const[f,setF]=useState<any>({product_id:'',material_id:'',target:'product',movement_type:'adjustment_in',quantity:'',jalali_date:todayJalali(),notes:''});
 const[m,setM]=useState<any>({name:'',unit:'کیلوگرم',current_unit_cost:'',min_stock:'0'});
 async function load(){const s=supabase();const[{data:p},{data:mats},{data:opts}]=await Promise.all([s.from('v_product_stock').select('*').order('name'),s.from('v_material_stock').select('*').order('name'),s.from('products').select('id,name,unit').eq('active',true).order('name')]);setProducts(p||[]);setMaterials(mats||[]);setProductOptions(opts||[])}
 useEffect(()=>{load()},[]);
 function reset(){setF({product_id:'',material_id:'',target:'product',movement_type:'adjustment_in',quantity:'',jalali_date:todayJalali(),notes:''});setMsg('')}
 async function saveMove(){const id=f.target==='product'?f.product_id:f.material_id;if(!id||!f.quantity){setMsg('کالا/ماده و مقدار الزامی است.');return}setBusy(true);const payload:any={movement_type:f.movement_type,quantity:Number(f.quantity),movement_date:new Date().toISOString().slice(0,10),jalali_date:f.jalali_date||todayJalali(),notes:f.notes||null,ref_type:'manual_adjustment'};if(f.target==='product')payload.product_id=f.product_id;else payload.material_id=f.material_id;const{error}=await supabase().from('inventory_movements').insert(payload);setBusy(false);if(error){setMsg(error.message);return}setOpenMove(false);reset();load()}
 async function saveMaterial(){if(!m.name.trim()){setMsg('نام ماده اولیه الزامی است.');return}setBusy(true);const{error}=await supabase().from('materials').insert({name:m.name.trim(),unit:m.unit||'کیلوگرم',current_unit_cost:Number(m.current_unit_cost||0),min_stock:Number(m.min_stock||0),active:true});setBusy(false);if(error){setMsg(error.message);return}setOpenMaterial(false);setM({name:'',unit:'کیلوگرم',current_unit_cost:'',min_stock:'0'});setMsg('');load()}
 return <><div className="title"><div><h1>انبار</h1><p>موجودی محصولات نهایی و مواد اولیه</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn" onClick={()=>{setMsg('');setOpenMaterial(true)}}>+ ماده اولیه</button><button className="btn" style={{background:'#333'}} onClick={()=>{reset();setOpenMove(true)}}>+ اصلاح موجودی</button></div></div>
 <div className="section"><h2 style={{fontSize:18}}>محصولات نهایی</h2><div style={{overflow:'auto'}}><table className="table"><thead><tr><th>محصول</th><th>واحد</th><th>موجودی قابل فروش</th><th>حداقل</th><th>وضعیت</th></tr></thead><tbody>{products.length?products.map((r:any)=><tr key={r.product_id}><td>{r.name}</td><td>{r.unit||'-'}</td><td>{n(r.available_stock)}</td><td>{n(r.min_stock)}</td><td>{Number(r.available_stock)<=Number(r.min_stock)?'نیاز به تولید/تأمین':'عادی'}</td></tr>):<tr><td colSpan={5} style={{textAlign:'center',padding:24}}>محصولی ثبت نشده است.</td></tr>}</tbody></table></div></div>
 <div className="section"><h2 style={{fontSize:18}}>مواد اولیه</h2><div style={{overflow:'auto'}}><table className="table"><thead><tr><th>ماده</th><th>واحد</th><th>موجودی</th><th>حداقل</th><th>آخرین بهای واحد</th><th>وضعیت</th></tr></thead><tbody>{materials.length?materials.map((r:any)=><tr key={r.material_id}><td>{r.name}</td><td>{r.unit}</td><td>{n(r.stock)}</td><td>{n(r.min_stock)}</td><td>{n(r.current_unit_cost)}</td><td>{Number(r.stock)<=Number(r.min_stock)?'نیاز به خرید':'عادی'}</td></tr>):<tr><td colSpan={6} style={{textAlign:'center',padding:24}}>هنوز ماده اولیه‌ای ثبت نشده است.</td></tr>}</tbody></table></div></div>
 <FormModal open={openMaterial} title="ثبت ماده اولیه" onClose={()=>setOpenMaterial(false)}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div className="field"><label>نام ماده *</label><input className="input" value={m.name} onChange={e=>setM({...m,name:e.target.value})}/></div><div className="field"><label>واحد</label><select className="input" value={m.unit} onChange={e=>setM({...m,unit:e.target.value})}><option>کیلوگرم</option><option>گرم</option><option>لیتر</option><option>عدد</option><option>متر</option><option>تن</option></select></div><div className="field"><label>بهای واحد فعلی</label><input className="input" type="number" min="0" value={m.current_unit_cost} onChange={e=>setM({...m,current_unit_cost:e.target.value})}/></div><div className="field"><label>حداقل موجودی</label><input className="input" type="number" min="0" value={m.min_stock} onChange={e=>setM({...m,min_stock:e.target.value})}/></div></div>{msg&&<div className="msg">{msg}</div>}<button className="btn" style={{width:'100%',marginTop:12}} disabled={busy} onClick={saveMaterial}>ثبت ماده اولیه</button></FormModal>
 <FormModal open={openMove} title="اصلاح موجودی" onClose={()=>setOpenMove(false)}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div className="field"><label>نوع موجودی</label><select className="input" value={f.target} onChange={e=>setF({...f,target:e.target.value,product_id:'',material_id:''})}><option value="product">محصول نهایی</option><option value="material">ماده اولیه</option></select></div>{f.target==='product'?<div className="field"><label>محصول *</label><select className="input" value={f.product_id} onChange={e=>setF({...f,product_id:e.target.value})}><option value="">انتخاب</option>{productOptions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>:<div className="field"><label>ماده اولیه *</label><select className="input" value={f.material_id} onChange={e=>setF({...f,material_id:e.target.value})}><option value="">انتخاب</option>{materials.map(x=><option key={x.material_id} value={x.material_id}>{x.name}</option>)}</select></div>}<div className="field"><label>نوع گردش</label><select className="input" value={f.movement_type} onChange={e=>setF({...f,movement_type:e.target.value})}><option value="adjustment_in">افزایش موجودی</option><option value="adjustment_out">کاهش موجودی</option><option value="return_in">برگشت به انبار</option><option value="return_out">خروج برگشتی</option><option value="waste">ضایعات</option></select></div><div className="field"><label>مقدار *</label><input className="input" type="number" step="0.01" min="0" value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})}/></div><div className="field"><label>تاریخ شمسی</label><input className="input" value={f.jalali_date} onChange={e=>setF({...f,jalali_date:e.target.value})}/></div></div><div className="field"><label>یادداشت</label><textarea className="input" rows={3} value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></div>{msg&&<div className="msg">{msg}</div>}<button className="btn" style={{width:'100%',marginTop:12}} disabled={busy} onClick={saveMove}>ثبت گردش</button></FormModal></>}
