'use client';
import {useEffect,useMemo,useState} from 'react';import {supabase} from '@/lib/supabase';import {toJalali,todayJalali} from '@/lib/jalali';import FormModal from '@/components/FormModal';
const money=(n:any)=>new Intl.NumberFormat('fa-IR').format(Number(n||0));
type Line={material_id:string;description:string;quantity:number;unit_price:number};const emptyLine:Line={material_id:'',description:'',quantity:1,unit_price:0};
export default function Purchases(){
 const[rows,setRows]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[materials,setMaterials]=useState<any[]>([]),[open,setOpen]=useState(false),[openSupplier,setOpenSupplier]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const[supplierId,setSupplierId]=useState(''),[jalali,setJalali]=useState(todayJalali()),[notes,setNotes]=useState(''),[lines,setLines]=useState<Line[]>([{...emptyLine}]);
 const[sp,setSp]=useState<any>({display_name:'',phone:'',city:'',address:''});
 async function load(){const s=supabase();const[{data:r},{data:p},{data:m}]=await Promise.all([s.from('purchase_invoices').select('id,purchase_no,invoice_date,jalali_date,total,notes,supplier:parties(display_name)').order('purchase_no',{ascending:false}).limit(200),s.from('parties').select('id,display_name').in('party_type',['supplier','both']).eq('active',true).order('display_name'),s.from('materials').select('id,name,unit,current_unit_cost').eq('active',true).order('name')]);setRows(r||[]);setSuppliers(p||[]);setMaterials(m||[])}
 useEffect(()=>{load()},[]);
 const total=useMemo(()=>lines.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.unit_price||0),0),[lines]);
 function chooseMaterial(i:number,id:string){const m=materials.find(x=>x.id===id);setLines(v=>v.map((x,n)=>n===i?{...x,material_id:id,description:m?.name||'',unit_price:Number(m?.current_unit_cost||0)}:x))}
 function patch(i:number,k:keyof Line,v:any){setLines(a=>a.map((x,n)=>n===i?{...x,[k]:v}:x))}
 async function saveSupplier(){if(!sp.display_name.trim()){setMsg('نام تأمین‌کننده الزامی است.');return}setBusy(true);const{error}=await supabase().from('parties').insert({party_type:'supplier',display_name:sp.display_name.trim(),phone:sp.phone||null,city:sp.city||null,address:sp.address||null,active:true});setBusy(false);if(error){setMsg(error.message);return}setOpenSupplier(false);setSp({display_name:'',phone:'',city:'',address:''});setMsg('');load()}
 async function save(){if(!supplierId){setMsg('تأمین‌کننده را انتخاب کنید.');return}const valid=lines.filter(l=>l.description.trim()&&Number(l.quantity)>0);if(!valid.length){setMsg('حداقل یک قلم خرید وارد کنید.');return}setBusy(true);setMsg('');const s=supabase();const{data:inv,error}=await s.from('purchase_invoices').insert({supplier_id:supplierId,invoice_date:new Date().toISOString().slice(0,10),jalali_date:jalali||todayJalali(),total,notes:notes||null}).select('id,purchase_no').single();if(error||!inv){setMsg('خطا در ثبت خرید: '+(error?.message||''));setBusy(false);return}const payload=valid.map(l=>({purchase_id:inv.id,material_id:l.material_id||null,description:l.description,quantity:Number(l.quantity),unit_price:Number(l.unit_price)}));const{error:e2}=await s.from('purchase_items').insert(payload);if(e2){await s.from('purchase_invoices').delete().eq('id',inv.id);setMsg('خطا در ثبت اقلام خرید: '+e2.message);setBusy(false);return}setBusy(false);setOpen(false);setSupplierId('');setJalali(todayJalali());setNotes('');setLines([{...emptyLine}]);load()}
 return <><div className="title"><div><h1>خرید و تأمین‌کنندگان</h1><p>ثبت فاکتور خرید، تأمین‌کننده و ورود خودکار مواد اولیه به انبار</p></div><div style={{display:'flex',gap:8}}><button className="btn" onClick={()=>{setMsg('');setOpenSupplier(true)}}>+ تأمین‌کننده</button><button className="btn" style={{background:'#333'}} onClick={()=>{setMsg('');setOpen(true)}}>+ ثبت خرید</button></div></div><div style={{overflow:'auto'}}><table className="table"><thead><tr><th>شماره</th><th>تاریخ</th><th>تأمین‌کننده</th><th>مبلغ</th><th>توضیحات</th></tr></thead><tbody>{rows.length?rows.map((r:any)=><tr key={r.id}><td>{r.purchase_no||'-'}</td><td>{r.jalali_date||toJalali(r.invoice_date)}</td><td>{r.supplier?.display_name||'-'}</td><td>{money(r.total)}</td><td>{r.notes||'-'}</td></tr>):<tr><td colSpan={5} style={{textAlign:'center',padding:24}}>هنوز خریدی ثبت نشده است.</td></tr>}</tbody></table></div>
 <FormModal open={openSupplier} title="ثبت تأمین‌کننده" onClose={()=>setOpenSupplier(false)}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div className="field"><label>نام *</label><input className="input" value={sp.display_name} onChange={e=>setSp({...sp,display_name:e.target.value})}/></div><div className="field"><label>موبایل</label><input className="input" value={sp.phone} onChange={e=>setSp({...sp,phone:e.target.value})}/></div><div className="field"><label>شهر</label><input className="input" value={sp.city} onChange={e=>setSp({...sp,city:e.target.value})}/></div><div className="field"><label>آدرس</label><input className="input" value={sp.address} onChange={e=>setSp({...sp,address:e.target.value})}/></div></div>{msg&&<div className="msg">{msg}</div>}<button className="btn" style={{width:'100%',marginTop:12}} disabled={busy} onClick={saveSupplier}>ثبت تأمین‌کننده</button></FormModal>
 <FormModal open={open} title="ثبت فاکتور خرید" onClose={()=>setOpen(false)}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div className="field"><label>تأمین‌کننده *</label><select className="input" value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">انتخاب تأمین‌کننده</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></div><div className="field"><label>تاریخ شمسی</label><input className="input" value={jalali} onChange={e=>setJalali(e.target.value)} placeholder="1405/06/17"/></div></div><div className="section"><b>اقلام خرید</b>{lines.map((l,i)=><div className="card" key={i} style={{marginTop:8,background:'#faf8f2'}}><div style={{display:'grid',gridTemplateColumns:'2fr 1fr',gap:8}}><select className="input" value={l.material_id} onChange={e=>chooseMaterial(i,e.target.value)}><option value="">انتخاب ماده / ورود دستی</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name} ({m.unit})</option>)}</select><button className="btn" style={{background:'#7b2d24'}} disabled={lines.length===1} onClick={()=>setLines(v=>v.filter((_,n)=>n!==i))}>حذف قلم</button></div><input className="input" style={{marginTop:8}} placeholder="شرح *" value={l.description} onChange={e=>patch(i,'description',e.target.value)}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}><div><small>مقدار</small><input className="input" type="number" step="0.01" value={l.quantity} onChange={e=>patch(i,'quantity',Number(e.target.value))}/></div><div><small>قیمت واحد</small><input className="input" type="number" value={l.unit_price} onChange={e=>patch(i,'unit_price',Number(e.target.value))}/></div></div><div style={{marginTop:8}}>جمع قلم: <b>{money(l.quantity*l.unit_price)}</b> تومان</div></div>)}<button className="btn" style={{marginTop:8,background:'#333'}} onClick={()=>setLines(v=>[...v,{...emptyLine}])}>+ افزودن قلم</button></div><div className="field"><label>توضیحات</label><textarea className="input" rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="card"><b>جمع خرید: {money(total)} تومان</b></div>{msg&&<div className="msg">{msg}</div>}<button className="btn" style={{width:'100%',marginTop:12}} disabled={busy} onClick={save}>ثبت نهایی خرید</button></FormModal></>}
